= Mysql cheatsheet
:toc:
:toc-placement: preamble
:toclevels: 1
:Some attr: Some value

// Need some preamble to get TOC:
{empty}

=== Create user

.Setting Password for MySQL Root User
[source,bash]
/usr/bin/mysqladmin -u root password 'new-password'
/usr/bin/mysqladmin -u root -h `hostname` password 'new-password'

.Creating User Accounts
[source,bash]
CREATE USER user;

.Adding Grants
[source,bash]
GRANT ALL ON mydb.* TO joebob@localhost;
GRANT ALL ON mydb.* TO joebob@"%";

.Setting Password for Other Users
[source,bash]
SET PASSWORD FOR joebob@localhost=PASSWORD('nochange');
SET PASSWORD FOR joebob@"%"=PASSWORD('nochange');

.Create a Database
[source,bash]
CREATE DATABASE mydb;
USE mydb;

=== Backup

.Делаем бекап
[source,bash]
mysqldump -u USER -pPASSWORD DATABASE > /path/to/file/dump.sql

.Создаём структуру базы без данных
[source,bash]
mysqldump --no-data - u USER -pPASSWORD DATABASE > /path/to/file/schema.sql

.Если нужно сделать дамп только одной или нескольких таблиц
[source,bash]
mysqldump -u USER -pPASSWORD DATABASE TABLE1 TABLE2 TABLE3 > /path/to/file/dump_table.sql

.Создаём бекап и сразу его архивируем
[source,bash]
mysqldump -u USER -pPASSWORD DATABASE | gzip > /path/to/outputfile.sql.gz
mysqldump -u USER -pPASSWORD DATABASE | bzip2 > /path/to/outputfile.sql.bz

.Создание бекапа с указанием его даты
[source,bash]
mysqldump -u USER -pPASSWORD DATABASE | gzip > `date +/path/to/outputfile.sql.%Y%m%d.%H%M%S.gz`

.Заливаем бекап в базу данных
[source,bash]
mysql -u USER -pPASSWORD DATABASE < /path/to/dump.sql

.Заливаем архив бекапа в базу
[source,bash]
gunzip < /path/to/outputfile.sql.gz | mysql -u USER -pPASSWORD DATABASE
.или так
zcat /path/to/outputfile.sql.gz | mysql -u USER -pPASSWORD DATABASE

.Создаём новую базу данных
[source,bash]
mysqladmin -u USER -pPASSWORD create NEWDATABASE

.Удобно использовать бекап с дополнительными опциями -Q -c -e, т.е.
[source,bash]
mysqldump -Q -c -e -u USER -pPASSWORD DATABASE > /path/to/file/dump.sql

где:

 * Q оборачивает имена обратными кавычками
 * c делает полную вставку, включая имена колонок
 * e делает расширенную вставку. Итоговый файл получается меньше и делается он чуть быстрее

.Для просмотра списка баз данных можно использовать команду:
[source,bash]
mysqlshow -u USER -pPASSWORD

.А так же можно посмотреть список таблиц базы:
[source,bash]
mysqlshow -u USER -pPASSWORD DATABASE

TIP: Для таблиц InnoDB надо добавлять +--single-transaction+, это гарантирует целостность данных бекапа.
Для таблиц MyISAN это не актуально, ибо они не поддерживают транзакционность.

.проброс портов
[source, bash]
ssh -fNL LOCAL_PORT:localhost:3306 REMOTE_USER@REMOTE_HOST

=== Optimisation

.Log slow queries
добавить следующие строки в */etc/my.cnf*:
[source,properties]
log-slow-queries=/tmp/slow_queries.log
long_query_time=10